language: python

python:
    - "2.6"
    - "2.7"
    - "3.4"

install:
    - pip install -r requirements_test.txt

script:
  - pep8 --ignore=E501 dictdiffer/*.py tests/*.py
  - pylint --rcfile=pylint.rc dictdiffer/*.py 
  - nosetests --with-coverage tests/*.py
